language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-flake8
    - python: 3.4
      env: TOXENV=py34-flake8
    - python: 3.5
      env: TOXENV=py35-flake8
    - python: 3.6
      env: TOXENV=py36-flake8
    - python: 3.6
      env: TOXENV=precommit
    - python: 3.6
      env: TOXENV=safety
    - python: 3.6
      env: TOXENV=mypy
    - python: 3.6
      env: TOXENV=compile-catalog
    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 2.7
      env: TOXENV=py27-dj110
    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.3
      env: TOXENV=py33-dj18
    - python: 3.4
      env: TOXENV=py34-dj18
    - python: 3.4
      env: TOXENV=py34-dj110
    - python: 3.4
      env: TOXENV=py34-dj111
    - python: 3.5
      env: TOXENV=py35-dj18
    - python: 3.5
      env: TOXENV=py35-dj110
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.5
      env: TOXENV=py35-djmaster
    - python: 3.6
      env: TOXENV=py36-dj18
    - python: 3.6
      env: TOXENV=py36-dj110
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.6
      env: TOXENV=py36-djmaster
    - python: pypy2.7-5.8.0
      env: TOXENV=pypy-dj18
    - python: pypy2.7-5.8.0
      env: TOXENV=pypy-dj110
    - python: pypy2.7-5.8.0
      env: TOXENV=pypy-dj111
    - python: pypy3.5-5.8.0
      env: TOXENV=pypy3-dj18
    - python: pypy3.5-5.8.0
      env: TOXENV=pypy3-dj110
    - python: pypy3.5-5.8.0
      env: TOXENV=pypy3-dj111
    - python: pypy3.5-5.8.0
      env: TOXENV=pypy3-djmaster

  allow_failures:
    - python: 3.5
      env: TOXENV=py35-djmaster
    - python: 3.6
      env: TOXENV=py36-djmaster
    - python: pypy3.5-5.8.0
      env: TOXENV=pypy3-djmaster

install:
  - pip install virtualenv tox coveralls

script:
  - tox

after_success:
  - coveralls
